### ISSUE TITLE
[sprint_dummy][story_dummy][topic_dummy] first issue for Ashish

### ISSUE THREAD

**Issue by gssirohi** [gssirohi/MoneyCircleRepository#1]
"Change the hello world title and commit your changes from a topic branch."
topic branch developer will create itself for commiting any chnages.

topic branch should be created from story_development_branch on which developer is working

Example: Ashish is working on story_development_branch1, Now he has one issue (topic) to work on
He will create a branch "topic_dummy" from story_development_branch1 and commit his changes from topic branch. Then if changes are fine . He will create a pull request from topic-->stroy_development

**Comment by ashishpal5588** [comment]
Issue Fixed

**Comment by gssirohi** [comment]
where is commit id for the changes?

**Comment by ashishpal5588** [comment]
Commit id->4b5698a086
