### ISSUE TITLE
[3H] Notification Handling

### ISSUE THREAD

**Issue by aroraprateek202112** [gssirohi/MoneyCircleRepository#77]

**Comment by aroraprateek202112** [comment]
No notification when Notification Activity visible
Notification message appending if multiple notifications are unseen
Count of Unseen+Not responded message

Handle: Currently drawer has to be create again if u want to see the proper count.

1d75077844d9bafe44bd2f743d47393155bc9c2e
f33cb3effa54f201b48db992b97fcf0f624a009b

**Comment by gssirohi** [comment]
@aroraprateek202112 if item is completed then close , if some partial implementation is pending then create new issue and attach it somewhere so see fit in schedule and assign it to yourself and do let everyone know about this.
