### ISSUE TITLE
[2H] Invite Contact  and Share items

### ISSUE THREAD

**Issue by ashishpal5588** [gssirohi/MoneyCircleRepository#84]

**Comment by ashishpal5588** [comment]
Invite of contact via 3rd party application completed.
Share item  implementation is in progress, dependency on item.

**Comment by gssirohi** [comment]
What is the dependency?

**Comment by gssirohi** [comment]
And Why cant you communicate with anyone about dependency?

**Comment by ashishpal5588** [comment]
Dependency on my module[Money item detail View] for sharing Money Item

**Comment by ashishpal5588** [comment]
Commit id :->commit 3fa54381d44a11fad3c118a1c3c43eedcc332afc

Updated share item, removal of action bar

**Comment by gssirohi** [comment]
@ashishpal5588  if item is completed then close , if some partial implementation is pending then create new issue and attach it somewhere so see fit in schedule and assign it to yourself and do let everyone know about this.
